### PR TITLE
A upset plot

### PR DESCRIPTION
**Pull request by gaospecial**
I improved my codes and, by the way, the codes of `oncoplot.R` to fix `check()` warnings/notes. Besides, several minor points are revised, including typo and the update of Rd document. Also, I added myself into the author list of this package.

I would like to suggest that the functions in this `aplotExtra` be named in the form of `a_` prefix and `_plot`  suffix, as I did in `a_upset_plot`. In that cases, these functions would not conflict with the corresponding ones in the other packages. For example, `upsetplot()` has also been defined in `enrichplot` package. If I use `upsetplot` here, a conflict should occur and it will no doubt make me annoying. 

Please check it.

### CODE REVIEW

**Comment by GuangchuangYu** [comment]
I prefer to use `fun2` for the function name.

**Comment by gaospecial** [comment]
我的方法相当于把 `aplot` 的包名拆成两个部分，中间加上图像的名字，意味着这个图形是通过 `aplot` 拼成的一个图形（a plot）的，读成“ei upset plot”，意思到位有创意，读音也很霸气。不再考虑一下？

**Comment by GuangchuangYu** [comment]
我先改成upset_plot吧。

如果是强行搞上aplot的话，我可能更倾向于`aplot_upset`这种。

**Comment by gaospecial** [comment]
是不是有点小纠结:smile:

**Pull request merged**
